#ifndef ENVCALLS_H
#define ENVCALLS_H

#define ENV_WRITE_CONSOLE 0
#define ENV_READ_CONSOLE 1
#define ENV_SET_GREEN_LED 2
#define ENV_SET_RED_LED 3
#define ENV_SET_BLUE_LED 4
#define ENV_SET_GPIO_PIN 5
#define ENV_TERMINATE_TASK 6

#endif
